name: Generate Snake Animation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: Larimcal  # Seu nome de usuário GitHub
          output: dist/github-contribution-grid-snake.svg  # Caminho onde o SVG será gerado

      - name: Save SVG as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snake-svg
          path: dist/github-contribution-grid-snake.svg  # Caminho onde o SVG foi gerado



name: Publish Snake Animation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download SVG Artifact
        uses: actions/download-artifact@v2
        with:
          name: snake-svg
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist

